name: Change Digest

on:
  push:
    branches: [ "main", "*" ]
  pull_request:

permissions:
  contents: write

jobs:
  digest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Generate digest
        env:
          GITHUB_EVENT_NAME: ${{ github.event_name }}
          GITHUB_SHA: ${{ github.sha }}
          GITHUB_BASE_SHA: ${{ github.event.pull_request.base.sha }}
          GITHUB_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        run: |
          python scripts/diff_digest.py
          echo "----"; ls -l reports/; echo "----"
          head -n 50 reports/last_changes.md || true

      - name: Upload artifact (PRs)
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/upload-artifact@v4
        with:
          name: last_changes
          path: reports/last_changes.md

      - name: Commit digest (pushes)
        if: ${{ github.event_name == 'push' }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add reports/last_changes.md
          git commit -m "ci: update last_changes.md" || echo "No changes to commit"
          git push
